<?php defined('BASEPATH') OR exit('No direct script access allowed');

class Theme_Basekit extends Theme {

    public $name			= 'BaseKit';
    public $author			= 'Joshua Pekera';
    public $author_website	= 'http://joshuapekera.com/';
    public $website			= 'http://joshuapekera.com/';
    public $description		= 'A prototyping base theme.';
    public $version			= '1.0';
	public $options 		= array(
			'show_breadcrumbs' => 	array('title' 		=> 'Show Breadcrumbs',
						  'description'   => 'Would you like to display breadcrumbs?',
						  'default'       => 'yes',
						  'type'          => 'radio',
						  'options'       => 'yes=Yes|no=No',
						  'is_required'   => TRUE),
			'bootstrap_modal' => 	array('title' 		=> 'Enable Modals',
						  'description'   => 'A streamlined, but flexible, take on the traditional javascript modal plugin with only the minimum required functionality and smart defaults.',
						  'default'       => 'yes',
						  'type'          => 'radio',
						  'options'       => 'yes=Yes|no=No',
						  'is_required'   => TRUE),
			'bootstrap_dropdown' => 	array('title' 		=> 'Enable Dropdowns',
						  'description'   => 'Add dropdown menus to nearly anything in Bootstrap with this simple plugin. Bootstrap features full dropdown menu support on in the navbar, tabs, and pills.',
						  'default'       => 'yes',
						  'type'          => 'radio',
						  'options'       => 'yes=Yes|no=No',
						  'is_required'   => TRUE),
			'bootstrap_scrollspy' => 	array('title' 		=> 'Enable Scrollspy',
						  'description'   => 'Use scrollspy to automatically update the links in your navbar to show the current active link based on scroll position.',
						  'default'       => 'yes',
						  'type'          => 'radio',
						  'options'       => 'yes=Yes|no=No',
						  'is_required'   => TRUE),
			'bootstrap_tab' => 	array('title' 		=> 'Enable Togglable tabs',
						  'description'   => 'Use this plugin to make tabs and pills more useful by allowing them to toggle through tabbable panes of local content.',
						  'default'       => 'yes',
						  'type'          => 'radio',
						  'options'       => 'yes=Yes|no=No',
						  'is_required'   => TRUE),
			'bootstrap_tooltip' => 	array('title' 		=> 'Enable Tooltips',
						  'description'   => 'A new take on the jQuery Tipsy plugin, Tooltips dont rely on images—they use CSS3 for animations and data-attributes for local title storage.',
						  'default'       => 'yes',
						  'type'          => 'radio',
						  'options'       => 'yes=Yes|no=No',
						  'is_required'   => TRUE),
			'bootstrap_popover' => 	array('title' 		=> 'Enable Popovers *',
						  'description'   => 'Add small overlays of content, like those on the iPad, to any element for housing secondary information.<br/>* Requires Tooltips to be included',
						  'default'       => 'yes',
						  'type'          => 'radio',
						  'options'       => 'yes=Yes|no=No',
						  'is_required'   => TRUE),
			'bootstrap_button' => 	array('title' 		=> 'Enable Buttons',
						  'description'   => 'Do more with buttons. Control button states or create groups of buttons for more components like toolbars.',
						  'default'       => 'yes',
						  'type'          => 'radio',
						  'options'       => 'yes=Yes|no=No',
						  'is_required'   => TRUE),
			'bootstrap_collapse' => 	array('title' 		=> 'Enable Collapse',
						  'description'   => 'Get base styles and flexible support for collapsible components like accordions and navigation.',
						  'default'       => 'yes',
						  'type'          => 'radio',
						  'options'       => 'yes=Yes|no=No',
						  'is_required'   => TRUE),
			'bootstrap_carousel' => 	array('title' 		=> 'Enable Carousel',
						  'description'   => 'Create a merry-go-round of any content you wish to provide an interactive slideshow of content.',
						  'default'       => 'yes',
						  'type'          => 'radio',
						  'options'       => 'yes=Yes|no=No',
						  'is_required'   => TRUE),
			'bootstrap_typeahead' => 	array('title' 		=> 'Enable Typeahead',
						  'description'   => 'A basic, easily extended plugin for quickly creating elegant typeaheads with any form text input.',
						  'default'       => 'yes',
						  'type'          => 'radio',
						  'options'       => 'yes=Yes|no=No',
						  'is_required'   => TRUE),
			'bootstrap_alert' => 	array('title' 		=> 'Enable Alert messages',
						  'description'   => 'The alert plugin is a tiny class for adding close functionality to alerts.',
						  'default'       => 'yes',
						  'type'          => 'radio',
						  'options'       => 'yes=Yes|no=No',
						  'is_required'   => TRUE),
			'bootstrap_transition' => 	array('title' 		=> 'Enable Transitions *',
						  'description'   => 'For simple transition effects, include bootstrap-transition.js once to slide in modals or fade out alerts.<br/>* Required for animation in plugins',
						  'default'       => 'yes',
						  'type'          => 'radio',
						  'options'       => 'yes=Yes|no=No',
						  'is_required'   => TRUE),
									);
}

/* End of file theme.php */
